# Generated by Django 5.0.6 on 2024-06-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_thread_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
