# Generated by Django 5.0.6 on 2024-06-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_profilemodel_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='AccountType',
        ),
    ]
